defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: src.agent.train.TrainAgent

logdir: ${oc.env:VLA_LOG_DIR}/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
name: paligemma_${data.dataset_mix}_tp${horizon_steps}
device: cuda
seed: 42
pretrained_model_path: /n/fs/llm-unc/.cache/paligemma-3b-pt-224
load_pretrained_weights: True
debug: False

data:
  dataset_mix: bridge
  data_path: /n/fs/llm-unc/data/resize_224
  window_size: ${cond_steps}
  action_horizon: ${horizon_steps}
  skip_unlabeled: True
  load_proprio: True
  shuffle_buffer_size: 500000
  num_parallel_calls: 200
  traj_transform_threads: 48
  traj_read_threads: 48

wandb:
  entity: ${oc.env:VLA_WANDB_ENTITY}
  project: train-vla
  run: ${now:%H-%M-%S}_${name}

n_epochs: 3
log_freq: 100
save_model_batch_freq: 10000000
save_model_epoch_freq: 1
learning_rate: 2e-5
lr_scheduler:
  first_cycle_steps: ${n_epochs}
  min_lr: ${learning_rate}
  warmup_steps: 0
weight_decay: 0
max_grad_norm: 1.0

num_inference_steps: 10
final_action_clip_value:

cond_steps: 1
horizon_steps: 4
action_dim: 7 # EEF_POS
proprio_dim: 7  # POS_EULER

image_token_index: 257152
ignore_index: -100
vocab_size: 257216
pad_token_id: 0
max_seq_len: 512  # image + text

image_text_hidden_size: 2048  # gemma
proprio_hidden_size: 512
action_hidden_size: 1024

vision:
  _target_: src.model.paligemma.siglip.SiglipVisionModel
  config:
    hidden_size: 1152 # siglip
    intermediate_size: 4304
    num_hidden_layers: 27
    num_attention_heads: 16
    num_channels: 3
    image_size: 224
    patch_size: 14
    layer_norm_eps: 1e-6
    attention_dropout: 0.0
    num_image_tokens: 256

vision_projector:
  _target_: src.model.paligemma.siglip.PaliGemmaMultiModalProjector
  config:
    vision_config:
      hidden_size: 1152
      projection_dim: ${image_text_hidden_size}

joint:
  _target_: src.model.vla.modules.JointModel
  config:
    hidden_sizes:
      - ${image_text_hidden_size}
      - ${proprio_hidden_size}
      - ${action_hidden_size}
    intermediate_sizes:
      - 16384 # gemma
      - 1024
      - 4096
    #
    num_hidden_layers: 18
    num_attention_heads: 8
    num_key_value_heads: 1
    head_dim: 256
    max_position_embeddings: 8192
    rms_norm_eps: 1e-6
    rope_theta: 10000.0
    attention_bias: False
    attention_dropout: 0.0
    pad_token_id: ${pad_token_id}
